---
- name: put nginx.repo
  copy:
    src: etc/yum.repos.d/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: install nginx
  yum: name={{ item }}
  with_items:
    - nginx
  notify: restart nginx

- name: remove config files
  file:
    dest: /etc/nginx/conf.d/default.conf
    state: absent
  notify: reload nginx

- name: start nginx automatically
  service:
    name: nginx
    state: started

- name: open port
  firewalld:
    port: 80/tcp
    permanent: true
    immediate: true
    state: enabled
