---
- name: restart mailoney
  systemd:
    name: mailoney.service
    state: restarted

- name: reload firewalld
  shell: firewall-cmd --reload
  register: result
  failed_when: '"success" not in result.stdout'
