---
- name: install postfix
  yum: name={{ item }}
  with_items:
    - postfix
  notify: restart postfix

- name: start postfix automatically
  systemd:
    name: postfix.service
    state: started
    daemon_reload: yes
    enabled: yes

- name: put config files
  template:
    src: '{{ item }}'
    dest: /etc/postfix/{{ item | basename | regex_replace('\.j2$','') }}
  with_fileglob:
    - ../templates/etc/postfix/*.j2
  notify: restart postfix

- name: open port
  firewalld:
    port: 25/tcp
    permanent: true
    immediate: true
    state: enabled
