---
- name: generate user password
  shell:
    test -f /home/honeypot/.password
    && cat /home/honeypot/.password
    || (cat /dev/urandom | tr -dc '[:alnum:]' | head -c 8)
  changed_when: False
  register: last_result

- name: set var
  set_fact:
    user_password: "{{ last_result.stdout }}"
  changed_when: False

- name: create group
  group:
    name: honeypot

- name: add user
  user:
    name: honeypot
    groups: honeypot
    password: "{{ user_password | password_hash('sha512') }}"
    update_password: on_create
    state: present

- name: put .password file
  template:
    src: home/honeypot/.password.j2
    dest: /home/honeypot/.password
    mode: "0600"

- name: install packages
  yum: name={{ item }}
  with_items:
    - firewalld
    - logrotate
    - http://ftp.riken.jp/Linux/fedora/epel/7/x86_64/Packages/e/epel-release-7-12.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: start firewalld automatically
  systemd:
    name: firewalld.service
    state: started
    daemon_reload: yes
    enabled: yes

- name: open port
  firewalld:
    port: "{{ ansible_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: install packages for pyenv
  yum: name={{ item }}
  with_items:
    - readline-devel
    - zlib-devel
    - libffi-devel
    - bzip2-devel
    - sqlite-devel
    - openssl-devel

- name: put pyenv scripts
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - usr/local/bin/pyenv-setup.sh
    - usr/local/bin/pyenv-switch.sh
